In [32]:
import rmllm
import pandas as pd

In [33]:
fig_path = rmllm.config.FIGURES_DIR/"svgs"
fig_path.mkdir(parents=True, exist_ok=True)

data_dir = rmllm.config.PROCESSED_DATA_DIR

exp_1 = pd.read_csv(data_dir / "rmai_exp_1.csv")
exp_2 = pd.read_csv(data_dir / "rmai_exp100_2.csv")
exp_2_r = pd.read_csv(data_dir / "rmai_exp100_2_r.csv")

In [34]:
exp_2

,order,tridx_test,trcode_test,source_test,trace,fb_inputs_test,Judgment_test,Confidence_test,Test_Word_test,model,...,subtask_ort,word2,word2acc,response feedback,rating feedback,overall feedback,response feedback_aligned,rating feedback_aligned,overall feedback_aligned,fb_trial_quality
0,1,10,test:imagined_1,test:imagined,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,sandpaper,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11,test:perceived_2,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,sugar,gemma3_12b,...,phase1,sweet,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,12,test:imagined_3,test:imagined,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,suburb,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,13,test:perceived_4,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,chair,gemma3_12b,...,phase1,cushion,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,14,test:perceived_5,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,letter,gemma3_12b,...,phase1,tip,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,1,35,test:perceived_16,test:perceived,20251102T21-38-41RMCONVO100Convorm_2op_convo_fb64,"{'response feedback': ""**CORRECT: Correct gene...",external,5.0,downy,llama4_scout,...,phase1,plush,True,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**CORRECT: Last trial was a perceived trial ty...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",True
35996,1,36,test:perceived_17,test:perceived,20251102T21-38-41RMCONVO100Convorm_2op_convo_fb64,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,england,llama4_scout,...,phase1,prince,True,**CORRECT: Last trial was a perceived trial ty...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**CORRECT: Last trial was a perceived trial ty...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",True
35997,1,37,test:imagined_20,test:imagined,20251102T21-38-41RMCONVO100Convorm_2op_convo_fb64,"{'response feedback': ""**INCORRECT: Correct ge...",internal,4.0,pane,llama4_scout,...,phase1,________,True,**CORRECT: Last trial was a perceived trial ty...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",True
35998,1,38,test:imagined_22,test:imagined,20251102T21-38-41RMCONVO100Convorm_2op_convo_fb64,"{'response feedback': ""**CORRECT: Correct gene...",external,5.0,gloves,llama4_scout,...,phase1,________,True,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35999,1,39,test:imagined_23,test:imagined,20251102T21-38-41RMCONVO100Convorm_2op_convo_fb64,"{'response feedback': ""**INCORRECT: Correct ge...",external,5.0,sluggish,llama4_scout,...,phase1,________,True,**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,NaN,NaN,NaN,NaN

In [35]:
exp_2_r

,order,tridx_test,trcode_test,source_test,trace,fb_inputs_test,Judgment_test,Confidence_test,Test_Word_test,model,...,subtask_ort,word2,word2acc,response feedback,rating feedback,overall feedback,response feedback_aligned,rating feedback_aligned,overall feedback_aligned,fb_trial_quality
0,2,10,test:imagined_1,test:imagined,20260118T12-15-51RRMCONVO100Convorm_2op_5t_con...,NaN,internal,6.0,sandpaper,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,11,test:perceived_2,test:perceived,20260118T12-15-51RRMCONVO100Convorm_2op_5t_con...,NaN,external,6.0,sugar,gemma3_12b,...,phase1,sweet,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,12,test:imagined_3,test:imagined,20260118T12-15-51RRMCONVO100Convorm_2op_5t_con...,NaN,internal,5.0,suburb,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,13,test:perceived_4,test:perceived,20260118T12-15-51RRMCONVO100Convorm_2op_5t_con...,NaN,external,6.0,chair,gemma3_12b,...,phase1,cushion,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,14,test:perceived_5,test:perceived,20260118T12-15-51RRMCONVO100Convorm_2op_5t_con...,NaN,internal,3.0,letter,gemma3_12b,...,phase1,tip,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,2,35,test:perceived_16,test:perceived,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,downy,llama4_scout,...,phase1,plush,False,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35996,2,36,test:perceived_17,test:perceived,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**INCORRECT: Correct ge...",external,5.0,england,llama4_scout,...,phase1,prince,False,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35997,2,37,test:imagined_20,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,pane,llama4_scout,...,phase1,________,True,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",True
35998,2,38,test:imagined_22,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,gloves,llama4_scout,...,phase1,________,True,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35999,2,39,test:imagined_23,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,sluggish,llama4_scout,...,phase1,________,True,**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,NaN,NaN,NaN,NaN

In [36]:
exp_2 = pd.concat([exp_2, exp_2_r])

In [37]:
exp_2

,order,tridx_test,trcode_test,source_test,trace,fb_inputs_test,Judgment_test,Confidence_test,Test_Word_test,model,...,subtask_ort,word2,word2acc,response feedback,rating feedback,overall feedback,response feedback_aligned,rating feedback_aligned,overall feedback_aligned,fb_trial_quality
0,1,10,test:imagined_1,test:imagined,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,sandpaper,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11,test:perceived_2,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,sugar,gemma3_12b,...,phase1,sweet,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,12,test:imagined_3,test:imagined,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,suburb,gemma3_12b,...,phase1,________,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,13,test:perceived_4,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,chair,gemma3_12b,...,phase1,cushion,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,14,test:perceived_5,test:perceived,20251104T10-13-51RMCONVO100Convorm_2op_convo_n...,NaN,external,6.0,letter,gemma3_12b,...,phase1,tip,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,2,35,test:perceived_16,test:perceived,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,downy,llama4_scout,...,phase1,plush,False,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35996,2,36,test:perceived_17,test:perceived,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**INCORRECT: Correct ge...",external,5.0,england,llama4_scout,...,phase1,prince,False,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35997,2,37,test:imagined_20,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,pane,llama4_scout,...,phase1,________,True,**INCORRECT: Last trial was a perceived trial ...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",True
35998,2,38,test:imagined_22,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,gloves,llama4_scout,...,phase1,________,True,**CORRECT: Last trial was a imagined trial typ...,**CORRECT: Your 'rating' value is in the instr...,"**CORRECT Answer!** **Well Answered, Good Job!**",**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,False
35999,2,39,test:imagined_23,test:imagined,20260120T01-41-03RRMCONVO100Convorm_2op_convo_...,"{'response feedback': ""**CORRECT: Correct gene...",internal,4.0,sluggish,llama4_scout,...,phase1,________,True,**INCORRECT: Last trial was a imagined trial t...,**CORRECT: Your 'rating' value is in the instr...,**INCORRECT Answer!** **Follow all the trial i...,NaN,NaN,NaN,NaN

In [38]:

model_map_1 = {
    "gemma3:12b":"Gemma3:12b",
    "gemma3:12b-it-qat":"Gemma3:12b-QAT",
    "gemma3:27b":"Gemma3:27b",
    "gemma3:27b-it-qat":"Gemma3:27b-QAT",
    "llama4:scout":"Llama4:16x17b",
    "llama3.3:70b":"Llama3.3:70b"
}
model_map_2 = {
    "gemma3_12b":"Gemma3:12b",
    "gemma3_12b-it-qat":"Gemma3:12b-QAT",
    "gemma3_27b":"Gemma3:27b",
    "gemma3_27b-it-qat":"Gemma3:27b-QAT",
    "llama4_scout":"Llama4:16x17b",
    "llama3.3_70b":"Llama3.3:70b"
}
exp_1["model"] = exp_1["model"].map(model_map_1)
exp_2["model"] = exp_2["model"].map(model_map_2)


exp_1["accuracy"] = exp_1["accuracy"].astype(int)
exp_2["accuracy"] = exp_2["accuracy"].astype(int)

exp_1["memory"] = exp_1["memory"].map({'SingleTurn':"SingleTurn", 'Convo':"TrialChain"})

exp_1["trial_compliance"] = exp_1["word2acc"].astype(int)
exp_1["reading_hallucination"] = 1 - exp_1["word2acc"].astype(int)

exp_2["trial_compliance"] = exp_2["word2acc"].astype(int)

exp_2["reading_hallucination"] = 1 - exp_2["word2acc"].astype(int)

exp_2["test_source"] = exp_2["source_test"]
exp_2["gen_source"] = exp_2["source_ort"]

exp_1.rename(columns={"Rating":"rating"},inplace=True)
exp_1.rename(columns={"Confidence":"confidence"},inplace=True)

exp_2.rename(columns={"Confidence_test":"confidence"},inplace=True)
exp_2.rename(columns={"Rating_ort":"rating"},inplace=True)

In [39]:
exp_1_grp = ["memory", "model", "source"]
exp_1["total_trials"] = exp_1.groupby(exp_1_grp)["trial_compliance"].transform("count")
exp_2_grp = ["trace","model","setsize","fb_exp","test_source"]
exp_2["total_trials"] = exp_2.groupby(exp_2_grp)["trial_compliance"].transform("count")

# Prepare Source Accuracy DataFrames for Analysis

In [40]:
# Experiment 1
exp1_src_accuracy = exp_1.groupby(exp_1_grp)[["total_trials","rating","reading_hallucination","accuracy","confidence"]].mean().reset_index()

In [41]:
# Experiment 2
exp2_src_accuracy = exp_2.pivot_table(index=exp_2_grp,values = ["total_trials","rating","reading_hallucination","accuracy","confidence"],aggfunc="mean").reset_index()

In [42]:
exp_2["total_trials"].unique()

array([ 5, 10])

In [43]:
exp2_src_accuracy

,trace,model,setsize,fb_exp,test_source,accuracy,confidence,rating,reading_hallucination,total_trials
0,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.0,6.0,84.7,0.0,10.0
1,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:perceived,1.0,6.0,59.4,0.0,10.0
2,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.0,1.0,81.6,0.0,10.0
3,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:perceived,1.0,1.0,59.0,0.0,10.0
4,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.2,5.9,85.9,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...
9595,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5.8,58.0,0.0,5.0
9596,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:imagined,1.0,4.6,90.4,0.0,5.0
9597,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5.8,58.0,0.0,5.0
9598,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:imagined,0.8,4.8,82.0,0.0,5.0
9599,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5.4,49.0,0.0,5.0

In [44]:
# Experiment 1
exp1_src_accuracy = exp_1.groupby(exp_1_grp).agg({
    'total_trials': 'first',  # Or 'mean' since it's constant per group
    'rating': 'mean',
    'reading_hallucination': ['mean', 'sum'],
    'accuracy': ['mean', 'sum'],
    'confidence': 'mean'
}).reset_index()

# Flatten multi-level columns
exp1_src_accuracy.columns = ['_'.join(col).strip() if col[1] else col[0] for col in exp1_src_accuracy.columns.values]

# Experiment 2
aggfunc = {
    'total_trials': 'first',  # Or 'mean' since it's constant per group
    'rating': 'mean',
    'reading_hallucination': ['mean', 'sum'],
    'accuracy': ['mean', 'sum'],
    'confidence': 'mean'
}
exp2_src_accuracy = exp_2.pivot_table(index=exp_2_grp, values=['total_trials', 'rating', 'reading_hallucination', 'accuracy', 'confidence'], aggfunc=aggfunc).reset_index()

# Flatten multi-level columns
exp2_src_accuracy.columns = ['_'.join(col).strip() if col[1] else col[0] for col in exp2_src_accuracy.columns.values]

# Prepare cumulative trial accuracy data for experiment 2

In [45]:
btw_groups2 = ["setsize","fb_exp","model","trace"]
exp_2["trial_count"] = exp_2.groupby(btw_groups2).cumcount()+1
exp_2["cum_acc_sum"] = exp_2.groupby(btw_groups2)["accuracy"].cumsum()
exp_2["cum_acc"] = exp_2["cum_acc_sum"]/exp_2["trial_count"]
exp_2_20 = exp_2.loc[exp_2["setsize"]==20]
exp_2_40 = exp_2.loc[exp_2["setsize"]==40]

# SAVE DATA

In [46]:
exp_1.to_csv(rmllm.config.PROCESSED_DATA_DIR/"exp1_trial_data.csv")
exp_2.to_csv(rmllm.config.PROCESSED_DATA_DIR/"exp2_trial_data.csv")

exp1_src_accuracy.to_csv(rmllm.config.PROCESSED_DATA_DIR/"exp1_group_level.csv")
exp2_src_accuracy.to_csv(rmllm.config.PROCESSED_DATA_DIR/"exp2_group_level.csv")

In [47]:
exp2_src_accuracy

,trace,model,setsize,fb_exp,test_source,accuracy_mean,accuracy_sum,confidence_mean,rating_mean,reading_hallucination_mean,reading_hallucination_sum,total_trials_first
0,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.0,0,6.0,84.7,0.0,0,10
1,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:perceived,1.0,10,6.0,59.4,0.0,0,10
2,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.0,0,1.0,81.6,0.0,0,10
3,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:perceived,1.0,10,1.0,59.0,0.0,0,10
4,20251101T18-54-45RMCONVO100Convorm_2op_convo_n...,Gemma3:12b,40,False,test:imagined,0.2,2,5.9,85.9,0.0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...
9595,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5,5.8,58.0,0.0,0,5
9596,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:imagined,1.0,5,4.6,90.4,0.0,0,5
9597,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5,5.8,58.0,0.0,0,5
9598,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:imagined,0.8,4,4.8,82.0,0.0,0,5
9599,20260120T09-38-49RRMCONVO100Convorm_2op_5t_con...,Llama3.3:70b,20,True,test:perceived,1.0,5,5.4,49.0,0.0,0,5

In [48]:
9600/4/6/2/2

100.0